name = "rateme"                     # Your project name
main = "src/worker.js"              # Entry point for your Worker
compatibility_date = "2026-01-20"   # Pick todayâ€™s date or when you last tested
type = "module" 

[durable_objects]
bindings = [
  { name = "MY_DURABLE_OBJECT", class_name = "MyDurableObject" }
]


[[kv_namespaces]]
binding = "USERS_KV"
id = "906909ed37a64c3c95b7c4b1fb8c3fb5"



[site]
bucket = "./public"
entry-point = "workers-site"
